Auth added
akp111/no-code-form-generator-backend pull request #5
Opened 2024-03-26 10:29 UTC by prvn347

I have added usermodel,signup and signin route with jwt auth and httponly cookie.

2024-03-29 15:26 UTC, akp111 commented on src/middleware/auth.ts
> +const app = express();
Try to keep it DRY, you can populate the application down to this instead of reinitialising

2024-03-29 15:30 UTC, akp111 commented on src/routes/user.ts
> +  } catch (error) {
Populate the error

2024-03-29 15:32 UTC, akp111 commented on src/services/users.ts
> +      const token = jwt.sign({ userId }, process.env.JWT_SECRET || "");
I would suggest, move all jwt related functions to a separate file. This would create a level of abstraction

2024-03-29 15:32 UTC, akp111 commented on src/services/users.ts
> +      const token = jwt.sign({ userId }, process.env.JWT_SECRET || "");
Move it to separate file related to jwt functions

2024-03-29 15:33 UTC, akp111 commented on src/services/users.ts
> +      if (error.name === "ValidationError") {
This error is getting repeated, so this can be a separate function itslef

2024-03-30 12:12 UTC, prvn347 commented
check now

2024-03-30 15:04 UTC, akp111 requested changes

2024-03-30 15:04 UTC, akp111 commented on src/middleware/auth.ts
> +    const payload = jwt.verify(
Verify function can be moved to jwt utila

2024-03-30 15:04 UTC, akp111 commented
@prvn347 , one small change and it is good to go

2024-03-30 16:49 UTC, prvn347 commented
@akp111 done

2024-03-30 16:53 UTC, merged